//! 业务资源模块（网络/空间/设备/链路/IP 等）。

pub mod cabinets;
pub mod cable_link;
pub mod device;
pub mod drawing;
pub mod employee;
pub mod ip;
pub mod net_outlet;
pub mod network;
pub mod options;
pub mod org_template;
pub mod organization;
pub mod patch_panel;
pub mod position;
pub mod room;
pub mod workstation;

pub use cabinets::*;
pub use cable_link::*;
pub use device::*;
pub use drawing::*;
pub use employee::*;
pub use ip::*;
pub use net_outlet::*;
pub use network::*;
pub use options::*;
pub use org_template::*;
pub use organization::*;
pub use patch_panel::*;
pub use position::*;
pub use room::*;
pub use workstation::*;
