version: "1.0"
name: CI
displayName: CI
stages:
- name: 基础检查
  displayName: 基础检查
  strategy: naturally
  trigger: auto
  steps:
  - step: build@rust
    name: build_rust_fmt
    displayName: Rust 代码格式化及检查
    rustVersion: "1.98"
    commands:
    - pwd
    - ls
    - ""
    - cargo fmt
    - ""
    - cargo fmt --check
    notify: []
    strategy:
      retry: "0"
      resource:
        cpu: "8"
        memory: "16"
  - step: build@rust
    name: build_rust_clippy
    displayName: Rust 静态检查
    rustVersion: "1.98"
    commands:
    - cargo clippy --release
    notify: []
    strategy:
      retry: "0"
  - step: build@rust
    name: build_rust_check
    displayName: Rust 构建测试
    rustVersion: "1.98"
    commands:
    - cargo check --release
    notify: []
    strategy:
      retry: "0"
  - step: build@rust
    name: build_rust_build
    displayName: Rust 单元测试
    rustVersion: "1.98"
    commands:
    - cargo test
    artifacts: []
    notify: []
    strategy:
      retry: "0"
- name: 正式构建
  displayName: 正式构建
  strategy: naturally
  trigger: auto
  steps:
  - step: build@rust
    name: 2ba8bbf9
    displayName: Rust 构建
    rustVersion: "1.98"
    commands:
    - cargo build --release
    artifacts:
    - name: BUILD_ARTIFACT
      path:
      - ./target/release/ipma
      type: .tar.gz
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
- name: 上传打包
  displayName: 上传打包
  strategy: naturally
  trigger: auto
  steps:
  - step: release@gitee
    name: 52cc1119
    displayName: Gitee Release
    releaseName: ""
    description: $description
    tagName: $tag
    upstreamArtifact:
    - BUILD_ARTIFACT
    assertFiles: []
    prerelease: false
    allowUpdate: true
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
triggers:
  trigger: auto
  push:
    tags:
      prefix:
      - ""
      precise: []
      include: []
notify: []
variables:
  RUSTUP_DIST_SERVER: https://mirrors.tuna.tsinghua.edu.cn/rustup
  RUSTUP_UPDATE_ROOT: https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
