version: "1.0"
name: 构建、上传、发布、部署到自有主机
displayName: 构建、上传、发布、部署到自有主机
stages:
- name: 构建
  displayName: 构建
  strategy: naturally
  trigger: auto
  steps:
  - step: build@rust
    name: ""
    displayName: Ruby 构建
    rustVersion: "1.93"
    commands:
    - '#代码格式化'
    - cargo fmt
    - ""
    - '#风格检查'
    - cargo clippy --release
    - ""
    - '#单元测试'
    - cargo test
    - ""
    - '#正式构建'
    - cargo build --release
    artifacts:
    - name: BUILD_ARTIFACT
      path:
      - ./target/release/ipma
      type: .tar.gz
    notify: []
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
- name: 上传
  displayName: 上传
  strategy: naturally
  trigger: auto
  steps:
  - step: publish@general_artifacts
    name: _1
    displayName: 上传制品
    dependArtifact: BUILD_ARTIFACT
    artifactName: output
    notify: []
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
- name: 发布
  displayName: 发布
  strategy: naturally
  trigger: auto
  steps:
  - step: publish@release_artifacts
    name: _2
    displayName: 发布
    dependArtifact: output
    version: 1.0.0.0
    autoIncrement: true
    notify: []
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
- name: 部署
  displayName: 部署
  strategy: naturally
  trigger: auto
  steps:
  - step: deploy@agent
    name: _3
    displayName: 主机部署
    deployArtifact:
    - name: output
      target: "~/gitee_go/deploy"
      source: artifact
      dependArtifact: ""
      artifactRepository: default
      artifactName: output
      artifactVersion: latest
    script: |-
      # 请在此输入部署脚本，如启动Java应用如下
      # nohup java -jar test.jar &gt; nohup.out &amp;
       echo 'Hello Gitee!'
    notify: []
    strategy:
      retry: "0"
triggers:
  trigger: manual
notify: []
strategy:
  blocking: true
